### ISSUE TITLE
Question - Constructing GraphQL queries

### ISSUE THREAD

**Issue by thecodeah** [erikvullings/strapi-to-typescript#12]
How would you go about generating the query?

Doing something like:
```ts
import { gql, useQuery } from "@apollo/client";

const GET_ARTICLES = gql`
    {
        articles {
            id
            published_at
            title
            content
            cover {
                url
            }
        }
    }
`;

// Somewhere else
const { loading, error, data } = useQuery(GET_ARTICLES);
```
would kind of defeat the whole point of generating interfaces for all the collections.

If I make a change to the collection, like deleting the `content` field. Then there would be hidden issues that I would only be able to discover during run-time.

Any suggestions? Am I missing something obvious? This is my first time using Strapi/GraphQL/Apollo

**Comment by aperron** [comment]
hello,

Sorry, i don't use graphQL, so it's hard for me to answer. Maybe you can import your type generated by strapi-to-typescript and use it with useQuery.

see doc @apollo/client [useQuery](https://www.apollographql.com/docs/react/development-testing/static-typing/)

something like
```javascript
import { Articles } from "./sts/articles"

// ...
const { loading, error, data } = useQuery<Articles>(GET_ARTICLES);
```

**Comment by thecodeah** [comment]
The query is still not typed, so that wouldn't resolved the issue. But thanks anyways
