### ISSUE TITLE
Fails with changed collection names

### ISSUE THREAD

**Issue by weidox** [erikvullings/strapi-to-typescript#13]
When collection name is changed, fails to match collection in other objects. Errors like
type 'mytype' unknown on somefield[mytype2] => fallback to 'any'. Add in the input arguments the folder that contains *.settings.json with info.name === 'mytype'
Plus fails to remove other symbols than spaces from collection names when generating interface names - that luckily can be fixed by providing a custom name generation function in interface (used plenty of dashes)

**Comment by weidox** [comment]
.name property is configurable. matching should be done by real collection name, which is folder name or prefix before *.settings.json file. Due to the same, custom interface name function in config could pass another parameter which is this real collection name, for full customization.

**Comment by aperron** [comment]
hello,

Could you share an example ?

_PS: a little 'hello' and/or a layout in your posts is always welcome :wink:_

**Comment by weidox** [comment]
/api/entry/models/entry.settings.json

{
  "kind": "collectionType",
  "collectionName": "entries",
  "info": {
    "name": "TBP - Entry"
  },
  "options": { 
.......

**Comment by weidox** [comment]
And for removing spaces and dashes, I wrote this in .stsconfig.js:
  `interfaceName: (name) => { const s = name.replace(/ |-/g, ''); return s[0].toUpperCase() + s.slice(1); },`
But it would be nice for the function would support another parameter, so it would be like
  `interfaceName: (name, key) => .....`, where name in my sample name could stay 'TBP - Entry' for some backwards compatibility, and key would be 'entry'.

**Comment by aperron** [comment]
ok, i'll try use [pluralize.singular()](https://www.npmjs.com/package/pluralize) used by Strapi to resolve name of collectionType with field collectionName.

**Comment by weidox** [comment]
That's an unreliable choice too because collection name may be modified and so different. Reliable way is to take file name and strip ".settings.json" from it.

**Comment by weidox** [comment]
Also it would be nice if it would allow to customize generated file name too, similar to interface name. But that probably could go into another ticket.

**Comment by weidox** [comment]
And relation types being generated as just "any" it seems to be pretty handy. Because when constructing new object, it's possible to assign just a string ID of another object. Or when controlled by "populate" parameter, whole object may be retrieved or just an ID instead. If types are generated like "field: Type | string", their access may become not so convenient in some cases. I think it would be best to have config option, whether to generate "any" or "field: Type" or "field Type | string" variant.

**Comment by weidox** [comment]
I tried to play with node-modules code a bit to see whether I could fix it myself. In importer.js I added this piece of code between first and last lines pasted below, to fix the original model name back to something like original (missing pluralize) - hacky way, if you're going to fix you may do something better, at least a new field.
        let strapiModel = Object.assign(JSON.parse(data), { _filename: f });
        const n1 = f.slice(f.lastIndexOf('\\') + 1) //windows
        const n2 = n1.slice(n1.lastIndexOf('/') + 1) //linux
        const n3 = n2.slice(0, n2.indexOf('.')) //cut all extensions
        strapiModel.info.name = n2
        if (strapiModel.info && strapiModel.info.name) {
After this change things start to almost work, there's only one failure on a component which was named "materials". It tries to make the name singular, and fails with error that "material" is not found. This whole idea of making singular from info.name is ill-fated, original model name from file name (or folder name) should be used without further conversions.

**Comment by weidox** [comment]
I may try next week

**Comment by weidox** [comment]
@aperron I have fix for this one and more, but unable to push branch as I don't have rights.

**Comment by weidox** [comment]
Seems I need to fork it first as I'm reading.. never did it here before. Will try later.

**Comment by weidox** [comment]
@aperron made a PR. Feel free to update it to match your guidelines. There is still one case unsolved (TODO in comments), I may take on it later.
