### ISSUE TITLE
Sometimes generates collection from node_modules instead of extensions

### ISSUE THREAD

**Issue by weidox** [erikvullings/strapi-to-typescript#16]
Randomly happens with User model which I have overridden. Most of the time works well, but sometimes after regenerating I'm finding original stuff from plugin which does not have all the fields I have added to User model.

**Comment by aperron** [comment]
No enough details

**Comment by weidox** [comment]
Getting randomly first or second error - expectation is to always get first error only, as extension overrides should take priority over node_modules:
1st error:
Already have model 'user' => skip .........\node_modules\strapi-plugin-users-permissions\models\User.settings.json use .........\extensions\users-permissions\models\User.settings.json
2nd error:
Already have model 'user' => skip .........\extensions\users-permissions\models\User.settings.json use .........\node_modules\strapi-plugin-users-permissions\models\User.settings.json

**Comment by aperron** [comment]
It seems to be related to parallel reading of files. It's fixed. To test in the next release
