### ISSUE TITLE
Content type with relation to itself tries to import itself causing an error

### ISSUE THREAD

**Issue by jdwholmes** [erikvullings/strapi-to-typescript#17]
I have a content type Treatment which has a relation to itself "parentTreatment" to create a hierarchy.

This results in the following being generated 

```typescript
import { ITreatment } from './treatment';

/**
 * Model definition for treatment
 */
export interface ITreatment {
  id: string;
  parentTreatment?: ITreatment;
}
```

This prevents the build due to ITreatment already being defined.

**Comment by aperron** [comment]
* which version are you using?
* could you share your `treatment.settings.json` to reproduce this issue ?

**Comment by jdwholmes** [comment]
Version: 2.0.4

`{
  "kind": "collectionType",
  "collectionName": "treatments",
  "info": {
    "name": "treatment",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "text"
    },
    "averagePrice": {
      "type": "decimal"
    },
    "parentTreatment": {
      "model": "treatment"
    },
    "showHome": {
      "type": "boolean",
      "default": false
    },
    "slug": {
      "type": "uid",
      "targetField": "name"
    }
  }
}
`

**Comment by aperron** [comment]
Could you try 2.0.5 ?

**Comment by jdwholmes** [comment]
Ah, sorry. My bad!
