### ISSUE TITLE
Generating non-model types?

### ISSUE THREAD

**Issue by thecodeah** [erikvullings/strapi-to-typescript#18]
How would I go about generating stuff like
```
    type UsersPermissionsLoginPayload {
      jwt: String
      user: UsersPermissionsMe!
    }

    type UserPermissionsPasswordPayload {
      ok: Boolean!
    }
```
:arrow_up: This is a snippet from `node_modules/strapi-plugin-users-permissions/config/schema.graphql.js`... In case you're wondering what the entire file looks like, click [here](https://gist.github.com/thecodeah/57cb8e435d27fa6cbede1bedb2ea8575)!

I can't find a `.settings.json` file containing those types anywhere. I even performed a search for the word `jwt` throughout the entire strapi directory and this is the only mention of it (Translation files aside)

I need this to handle authentication response data

**Comment by aperron** [comment]
Hello, 
Sorry for the response time.

The type `UsersPermissionsLoginPayload` seems to be defined in:
`node_modules/strapi-plugin-users-permissions/documentation/1.0.0/overrides/users-permissions-User.json`

You may be able to define your own  `UsersPermissionsLoginPayload`. `UsersPermissionsMe` type can be generated with strapi-to-typescript with `node_modules/strapi-plugin-users-permissions/models/User.settings.json`
