### ISSUE TITLE
Please add strapi components

### ISSUE THREAD

**Issue by maxbaluev** [erikvullings/strapi-to-typescript#2]

**Comment by aperron** [comment]
Done in v1.0.0 release

**Comment by Juanmabs22** [comment]
I just have run `sts api/ -o api_ts/models/` but the components is not generating data:

Here is the strapi web admin:
![image](https://user-images.githubusercontent.com/5569316/87252879-c47e0680-c476-11ea-867c-8f1d5f8fcd85.png)

Here is the generated interfaced, note that the comoponent `RegisterData` is typed by any instead other type.
![image](https://user-images.githubusercontent.com/5569316/87252894-df507b00-c476-11ea-9b4a-372f046af5ab.png)

Now the components are in ./components not in api folder.
![image](https://user-images.githubusercontent.com/5569316/87252903-f0998780-c476-11ea-937f-c6d1491798e8.png)

```
/**
 * Model definition for Register
 */
export interface IRegister {
  id: string;
  Pictures: any[];
  PolicePictures: any[];
  createdTime?: Date;
  PDFpolice: any[];
  PDFgenerated: any[];
  PoliceNotified?: boolean;
  Printed?: boolean;
  RegisterData?: any;
}
```

I have run with:
- strapi 3.0.5
- strapi-to-typescript 1.0.1



Full package.json:
```json
{
  "name": "my-project",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi",
    "gen-ts-interfaces": "sts api/ -o api_ts/models/",
    "build-ts": "tsc"
  },
  "devDependencies": {
    "strapi-to-typescript": "^1.0.1"
  },
  "dependencies": {
    "knex": "<0.20.0",
    "reflect-metadata": "^0.1.13",
    "sqlite3": "latest",
    "strapi": "3.0.5",
    "strapi-admin": "3.0.5",
    "strapi-connector-bookshelf": "3.0.5",
    "strapi-plugin-content-manager": "3.0.5",
    "strapi-plugin-content-type-builder": "3.0.5",
    "strapi-plugin-documentation": "3.0.5",
    "strapi-plugin-email": "3.0.5",
    "strapi-plugin-entity-relationship-chart": "^0.2.0",
    "strapi-plugin-graphql": "3.0.5",
    "strapi-plugin-upload": "3.0.5",
    "strapi-plugin-users-permissions": "3.0.5",
    "strapi-utils": "3.0.5",
    "tsyringe": "^4.3.0"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "a8d8b8f0-49c1-4f74-bf70-dec7530dc4f0"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by aperron** [comment]
Hello, have you try the command line option `-g` ?

**Comment by Juanmabs22** [comment]
> @Juanmabs22 : Hello, have you try the command line option `-g` ?

Yes, same result.

**Comment by aperron** [comment]
> > @Juanmabs22 : Hello, have you try the command line option `-g` ?
> 
> Yes, same result.

Could you paste the full command used with the option  `-g`

**Comment by aperron** [comment]
@Juanmabs22  Component with PascalCase/CamelCase naming is converted in snakeCase by strapi. I try to fix this. You can rename `registerData` in `registerdata`, this should be fix this problem temporally.

**Comment by Juanmabs22** [comment]
> > > @Juanmabs22 : Hello, have you try the command line option `-g` ?
> > 
> > 
> > Yes, same result.
> 
> Could you paste the full command used with the option `-g`

`sts api/ -o api_ts/models/ -g`



Thanks for your support.

> @Juanmabs22 Component with PascalCase/CamelCase naming is converted in snakeCase by strapi. I try to fix this. You can rename `registerData` in `registerdata`, this should be fix this problem temporally.

Still same result, I think the components is not being processed. 

I attach the project if you could check the problem.
[my-project.zip](https://github.com/erikvullings/strapi-to-typescript/files/4932975/my-project.zip)

Now is not important due I'm working on a personal project :).

**Comment by aperron** [comment]
@Juanmabs22 : Just add folder of Strapi components. `sts api/ -o api_ts/models/ -g components/`

**Comment by Juanmabs22** [comment]
> @Juanmabs22 : Just add folder of Strapi components. `sts api/ -o api_ts/models/ -g components/`

Thanks! It's works like a charm.
Thanks for supporting me.
