### ISSUE TITLE
Altering generated file name?

### ISSUE THREAD

**Issue by RussellSanders1** [erikvullings/strapi-to-typescript#23]
Is there a feature that supports the same kind of option for file name as field/interface name?  I am not at liberty to change the names from strapi directly.

For clarity, I mean an option in stsconfig like ```fileName: (fileName) => `Changed${fileName}`;```

**Comment by aperron** [comment]
At the moment it is not possible to configure the name of the output files.
I don't have time to do it right away. I note your request. Do not hesitate to make a Pull Request, if you can.

**Comment by aperron** [comment]
see [v2.0.7](https://github.com/erikvullings/strapi-to-typescript/releases/tag/v2.0.7)
