### ISSUE TITLE
Fails to link component types in generated interfaces

### ISSUE THREAD

**Issue by jkerys-halo** [erikvullings/strapi-to-typescript#26]
Hello,

That's a little miss to properly link component types from what was fixed in 2.0.6. API models have files ending with ".settings.json" but components with just ".json". A little fix gets around that (I may make a PR if you think it's worth it, but you could just incorporate that change).
In ts-exporter.ts
```
    this.strapiModels = strapiModelsParse.map(m => {
      return {
        ...m,
        snakeName: m.info.name
          .split(/(?=[A-Z])/)
          .join('-')
          .replace(/[\/\- ]+/g, "-")
          .toLowerCase(),
        interfaceName: util.toInterfaceName(m.info.name, m._filename),
        modelName: path.basename(m._filename, '.settings.json')
      }
    });
```
change the modelName to
```
modelName: m._filename.endsWith('.settings.json') ? path.basename(m._filename, '.settings.json') : path.basename(m._filename, '.json')
```

**Comment by aperron** [comment]
see #24

**Comment by jkerys-halo** [comment]
@aperron yes it's duplicate, have missed that. Thing is that the quick fix is provided in this ticket.. You could just take it and release, without much waiting.
