### ISSUE TITLE
Fail when collection relates to itself - old issue again

### ISSUE THREAD

**Issue by jkerys-halo** [erikvullings/strapi-to-typescript#27]
This was reported under #14 and #17, fixed in 2.0.5, and appeared again in 2.0.6.

When there are links between users, user.ts is generated with this line
import { User } from './user';

**Comment by aperron** [comment]
Could you retry with [v2.0.7](https://github.com/erikvullings/strapi-to-typescript/releases/tag/v2.0.7) or follow this [instruction](https://github.com/erikvullings/strapi-to-typescript#issue)

**Comment by jkerys-halo** [comment]
@aperron with 2.0.7 everything is broken, wrong slash symbol direction (on Windows at least). It generates now as
`import { User } from '.\user';`

**Comment by aperron** [comment]
i pushed an other release v2.0.8  
I don't work on Windows :relieved:  So, i need more test on this to fix slash/unslash issue. At first glance, I used the path separator which depends on the OS => bad idea . I'll change that quickly.

For the other issue with bad import himself. Could you follow [this](https://github.com/erikvullings/strapi-to-typescript#issue)

**Comment by jkerys-halo** [comment]
Just tested 2.0.8, extra import is still there. But #24 was fixed with 2.0.8, that's great as I think it was much more complex issue that an extra import or wrong slash.

**Comment by jkerys-halo** [comment]
I'm trying to figure out how to follow those instructions, one thing I notice that there's 3 existing tests and they're failing because test number 3 throws an error that `inputGroup` is deprecated.

**Comment by aperron** [comment]
I use a console.warn to display the modification of option inputGroup -> component and test fall KO. I'll fix this.  
This change is not in release v2.0.8, just on master branch  
Thanks for your feedback on component names.

Unfornutally, my code is not friend with Windows and I'm going to need a little more time to run and fix this :cry:

**Comment by jkerys-halo** [comment]
I pushed config sample from my code, which could be used for cementing a test.
On windows stuff, I think you just need to get back to a static and not os-dependent slash as it was before. Won't have tests on that one anyway. As I checked code, use `/` instead of `path.sep` in `strapiModelExtractImports` in tsexporter. Other places using `path.sep` should be right because those are dealing with real file paths.

**Comment by aperron** [comment]
are you running with gitbash or cygwin? For me, everything is ko under windows.

**Comment by aperron** [comment]
see v2.0.9

**Comment by jkerys-halo** [comment]
Just tried 2.0.9, all working.
I'm working on windows and using WSL2 for some tasks, I'm running original Ubuntu in it. Kind of virtual machine, but very well integrated (part of windows), with 2 way file system access (and still some quirks due to mismatch of file security capabilities) and port forwarding.
