### ISSUE TITLE
Dynamic zone, Date types bug

### ISSUE THREAD

**Issue by Carduelis** [erikvullings/strapi-to-typescript#33]
> First of all, I would like to say a big thank you for the quick solutions of my previous issues.

I notices couple of errors regarding the current types generation.

## Dynamic zone

Strapi generates it always as an array of component-types. But the current implementation differs:

```
dynamicZone?: (IComponentA|IComponentB);
```

Which produces conflicts , and the real type should be like:
```
dynamicZone: (
    | IComponentA
    | IComponentB
  )[];

// or
dynamicZone: Array<IComponentA|IComponentB>
```

## Date type
The plugin generates it as a `Date` type, but in real it's just a string.

## JSON type
It's not a bug, but it's a suggestion to improve. 
Right now json is typed as 
```
{ [key: string]: any }
```

but the better solution is:
```
type JsonPrimitive = string | number | boolean | null
interface JsonMap extends Record<string, JsonPrimitive | JsonArray | JsonMap> {}
interface JsonArray extends Array<JsonPrimitive | JsonArray | JsonMap> {}
type Json = JsonPrimitive | JsonMap | JsonArray
```

**Comment by scmx** [comment]
I'm also running into the dynamic zone problem. I will try send a pull request.

**Comment by aperron** [comment]
Thanks for your feedback.

* Dynamic zone 
 see PR #35 

*  Date type & JSON type
this can be quite easily configured via the [advanced-configuration](https://github.com/erikvullings/strapi-to-typescript#advanced-configuration).fieldType ?

**Comment by aperron** [comment]
see 2.0.10
