### ISSUE TITLE
type 'file' unknown

### ISSUE THREAD

**Issue by RemyMachado** [erikvullings/strapi-to-typescript#37]
This issue is addressing a feature request.
- generate media models.

### Steps to reproduce:
- add a media field to a component.

### Context:
I created a media field (image only) on one of my components, but it seems that STS couldn't generate the resulting native `file` type given by Strapi models.

`type 'file' unknown on IMenu_entry[icon] => fallback to 'any'. Add in the input arguments the folder that contains *.settings.json with info.name === 'file'`

Here's my component `icon` field (media) inside `components/menu-entry.json`:
```json
"icon": {
      "model": "file",
      "via": "related",
      "allowedTypes": [
        "images"
      ],
      "plugin": "upload",
      "required": true,
      "pluginOptions": {}
}
```

The `file` type should look something like this (judging by the api response):
```json
"icon": {
        "id": 1,
        "name": "some-icon.svg",
        "alternativeText": "",
        "caption": "",
        "width": 512,
        "height": 512,
        "formats": null,
        "hash": "some_icon_3faea55b59",
        "ext": ".svg",
        "mime": "image/svg+xml",
        "size": 4.28,
        "url": "/uploads/some_icon_3faea55b59.svg",
        "previewUrl": null,
        "provider": "local",
        "provider_metadata": null,
        "created_at": "2021-06-09T13:10:26.000Z",
        "updated_at": "2021-06-09T13:10:26.000Z"
}
```

**Did I miss a way to connect STS to strapi native models or is it just not supported yet or impossible to implement?**

Also, I thank you for this amazing tool. I feel like STS could be part of the official Strapi organization as it's a must have for TypeScript frontend integrations!

**Comment by aperron** [comment]
what is your strapi-to-typescript configuration used ?

see [example advanced-configuration](https://github.com/erikvullings/strapi-to-typescript#advanced-configuration)
```javascript
    input: [
      'api',
      './node_modules/strapi-plugin-users-permissions/models/',
      './node_modules/strapi-plugin-upload/models/',
      './extensions/users-permissions/models/'
    ],
```

**Comment by RemyMachado** [comment]
I wasn't using the configuration file. I was giving components location with the `-g` parameter.


It works like a charm with the configuration file. Also, I had to manually add the `models` folder inside `./extensions/users-permissions` for the tool not to crash, but I saw that it has already been addressed in another issue.

Thank you very much. I hope this issue will help people than didn't want to use the config file at first.

**Comment by aperron** [comment]
maybe you don't need configuration file. Just add multi input. Example:
`sts input_1 input_2 input_3 -g components`
` sts api ./node_modules/strapi-plugin-users-permissions/models/ ./node_modules/strapi-plugin-upload/models/ -g components`
