### ISSUE TITLE
Question: __typename and how handle it with Typescript

### ISSUE THREAD

**Issue by SalahAdDin** [erikvullings/strapi-to-typescript#38]
Hello,

I'm working on migrate my portfolio from **JS** to **TS** and i got the next problem:
I have a model with a dynamic zone as follows:
```typescript
export interface IPage {
  id: string;
  title?: string;
  slug: string;
  thumbnail?: IFile;
  body: (
    | ({ __component: "content.rich-text" } & IRichText)
    | ({ __component: "content.experience" } & IExperience)
    | ({ __component: "content.personal-information" } & IPersonalInformation)
    | ({ __component: "fields.skill" } & ISkill)
  )[]; // IComponent[]
  tags?: ITag[];
  description?: string;
}
```

I have a component how renderizes this body:
```javascript
export const Body = ({ body }) => {
  return body.map((component) => (
    <DynamicZone key={`component${component.id}`} component={component} />
  ));
};
```

And the dynamic zone component is:
```javascript
export const DynamicZone = ({ component, className }) => {
  const classes = useStyles();
  const { i18n } = useTranslation();

  return (
    <Typography
      variant="body1"
      component="section"
      className={clsx(classes.root, className)}
    >
      {
        {
          ComponentContentContent: (
            <Content>
                component
            </Content>
          ),
          ComponentFieldsSkill: <Skill {...component} />,
        }[component.__typename]
      }
    </Typography>
  );
};
```

It is like that since the normal **GraphQL** _json_ response comes like:
```json
"body": [
        {
          "__typename": "ComponentContentPersonalInformation",
          "id": "2",
          "name": "José Luis Sandoval Alaguna",
          "photo": {
            "alternativeText": "Profile photo.",
            "caption": "José Luis Sandoval Alaguna",
            "url": "https://res.cloudinary.com/dqhx2k8cf/image/upload/v1608399687/fotodeperfil_029e62c5d9.jpg",
            "width": 970,
            "height": 1296
          },
          "position": "Front-End Developer at CloudNesil",
          "nationality": "Colombian",
          "address": {
            "address": "6438 Sokak. Yunusemre Mah. No: 5 Daire: 1, Pamukkale",
            "city": "Denizli",
            "country": "Turkey",
            "postalCode": null
          },
          "telephone": [
            {
              "id": "1",
              "type": "Mobile",
              "number": 5373749236
            }
          ],
          "mail": "alagunasalahaddin@live.com",
          "links": [
            {
              "id": "1",
              "type": "LinkedIn",
              "url": "www.linkedin.com/in/jluissalaguna/"
            },
            {
              "id": "2",
              "type": "Github",
              "url": "www.github.com/SalahAdDin"
            },
            {
              "id": "3",
              "type": "StackOverflow",
              "url": "stackoverflow.com/users/3826549/salahaddin"
            }
          ],
          "aboutMe": null
        },
        {
          "__typename": "ComponentFieldsSkill",
          "type": "Language",
          "id": "6",
          "name": "Español (Native)",
          "level": 5
        },
```

Hance, following the format and the generated **TypeScript** model, how can must i handle this?

Why does this package not export the `__typescript` field?

Thanks

**Comment by aperron** [comment]
Hello,

I don't use graphQL or DynamicZone but maybe you can add the field `__typename` with  the [advanced configuration](https://github.com/erikvullings/strapi-to-typescript#advanced-configuration) `addField` ?

The field `__typename` is present on REST endpoint ?

I can add an other argument to the `addField`  call to make it easier. For the moment, only the name of the interface is given.

**Comment by SalahAdDin** [comment]
> Hello,
> 
> I don't use graphQL or DynamicZone but maybe you can add the field `__typename` with the [advanced configuration](https://github.com/erikvullings/strapi-to-typescript#advanced-configuration) `addField` ?
> 
> The field `__typename` is present on REST endpoint ?
> 
> I can add an other argument to the `addField` call to make it easier. For the moment, only the name of the interface is given.

The field `__typename` should be present also on the _REST_ endpoint since it is part of the **_Dynamic Zone_**.

**Comment by aperron** [comment]
I don't see in [official documentation](https://strapi.io/documentation/developer-docs/latest/developer-resources/content-api/content-api.html#create-an-entry) . Only a little reference of this field in graphql doc :thinking: 

Have you try with `addField` conf ?

**Comment by svrin** [comment]
My experience is that only the __component on dynamic zone fields are available, but not __typename.

**Comment by aperron** [comment]
@svrin thanks for your feedback
