### ISSUE TITLE
Would be helpful to get created_at and updated_at to be added to generated models

### ISSUE THREAD

**Issue by jkerys-halo** [erikvullings/strapi-to-typescript#40]
Based on "timestamps" property in model (which may be "true" for default names by relational vs mongo, or array of created/updated field names).

**Comment by willnode** [comment]
I'm achiving this using `package-patch`

```diff
diff --git a/node_modules/strapi-to-typescript/dist/ts-exporter.js b/node_modules/strapi-to-typescript/dist/ts-exporter.js
index 66d6bb1..7c2bca2 100644
--- a/node_modules/strapi-to-typescript/dist/ts-exporter.js
+++ b/node_modules/strapi-to-typescript/dist/ts-exporter.js
@@ -194,6 +194,10 @@ class Converter {
                     continue;
                 result.push(`  ${this.strapiModelAttributeToProperty(m.interfaceName, aName, m.attributes[aName])}`);
             }
+            if (m.options && m.options.timestamps) {
+                result.push(`  created_at?: Date;`);
+                result.push(`  updated_at?: Date;`);
+            }
         if (util.addField) {
             let addFields = util.addField(m.interfaceName);
             if (addFields && Array.isArray(addFields))
```

I think i'm gonna create a PR for this.

**Comment by jkerys-halo** [comment]
It also needs a global flag (in stsconfig) to indicate whether it's for postgres or mongo (where these field names do differ). Default should be mongo by now, as "id" fields are generated as strings (to get ids as numbers requires messing with stsconfig). In postgres fields are named created_at/updated_at, and in mongo createdAt/updatedAt.

**Comment by aperron** [comment]
cf: #5 

> With v2.X you can add them, use the advanced configuration addField

**Comment by jkerys-halo** [comment]
This is not the same. While it is possible to use `addField`, it would add same fields for all entities. Configuration exists in `*.settings.json` files, it's hidden in `.options.timestamps` properties - as @willnode tried to use them, though also not very correctly. Field names can also be changed in that property - like I'm using for postgres:
```
    "timestamps": [
      "createdAt",
      "updatedAt"
    ],
```
That said, this may be low priority feature to add parsing of `timestamps` property, as `addField` can be used to get around for most common cases.
