### ISSUE TITLE
Add support for Strapi version 4

### ISSUE THREAD

**Issue by dmitrybelyakov** [erikvullings/strapi-to-typescript#49]
Creating a new issue since there's no way to reopen #47.

@chris-schra kindly provided a fix via #48 , however even with the fix `strapi-to-typescript` fails to generate types for Strapi 4.

Anything that used to go under `api` directory now lives under `src/api` and has a different folder structure, as such all strapi content types get ignored entirely and you get an empty `index.ts` file as a result.

**Comment by galago** [comment]
yeah, hope there's a fix soon

**Comment by johngribbin** [comment]
Any movement on this issue? Or does anyone know of alternative library to generate types for strapi v4? 

I noticed this commit - https://github.com/erikvullings/strapi-to-typescript/commit/5de0978492b61294447d118cdd798f87a8b84cb8

But still not working for me,

Thanks in advance!

**Comment by exposuredeveloper** [comment]
I've created this node app that creates Typescript types for Strapi 4, if anyone is interested: https://github.com/francescolorenzetti/types-4-strapi

**Comment by francescolorenzetti** [comment]
I've created this Node.js script that creates Typescript types for Strapi 4, if anyone is interested: 

https://github.com/francescolorenzetti/types-4-strapi

**Comment by kerwanp** [comment]
Would be incredible to have support for V4!

**Comment by weidox** [comment]
May be pointless at this time as I saw there was announcement for beta typescript support in Strapi itself. So Strapi 4 soon won't need external tools for typescript.

**Comment by dmitrybelyakov** [comment]
@weidox agreed, we ended up generating types from the graphql schema which seems to work quite well (requires graphql plugin for strapi). I will close this.

**Comment by moussaab-moulim** [comment]
i dont think 

> @weidox agreed, we ended up generating types from the graphql schema which seems to work quite well (requires graphql plugin for strapi). I will close this.

the types that are generated from graphql schema are different from the types you get from rest api 
per example in graphql schema you dont get __component that exists in rest api which contains the component type

graphql and rest dont have the same schemas
