### ISSUE TITLE
Strapi v4 support?

### ISSUE THREAD

**Issue by greegus** [erikvullings/strapi-to-typescript#50]
Does this tool already support v4? I've been trying to use it in my project but only an empty `sts/index.ts` was generated. A quick peek into the source looked like it does not search for the `schema.json`.

I've run the sts as a script from `package.json` as follows:
```
"scripts": {
  "srs": "sts ./src -o ./sts"
}

**Comment by aperron** [comment]
Sorry, Strapi v4 is not supported. I will add a message to make it clear. 

see #49

**Comment by greegus** [comment]
👍
